#sudo service docker restart
#verfier si network existe si true on le suprime
version: "2.1"
services:
  #mysqlimage
  mysqlimage:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    image:
      mysqlimage
    networks:
      - dbproject
    container_name: mysqlcontainer
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 5
      

  #nodeimage    
  nodeimage:
    build:
      context: ./app-nodeapi/
      dockerfile: Dockerfile
    restart: always
    image:
      nodeimage
    container_name: nodecontainer
    ports:
    - "5000:3000"
    volumes:
    - ./app-nodeapi/appnode/:/usr/src/app/appnode
    networks:
      - dbproject
    depends_on:
      mysqlimage:
        condition: service_healthy
    
  
  
#delete network
networks:
  dbproject:
    driver: bridge